/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecorrenciasRouteImport } from './routes/recorrencias'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as IndexRouteImport } from './routes/index'

const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorrenciasRoute = RecorrenciasRouteImport.update({
  id: '/recorrencias',
  path: '/recorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/faturas': typeof FaturasRoute
  '/importacoes': typeof ImportacoesRoute
  '/insights': typeof InsightsRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/recorrencias': typeof RecorrenciasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/faturas': typeof FaturasRoute
  '/importacoes': typeof ImportacoesRoute
  '/insights': typeof InsightsRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/recorrencias': typeof RecorrenciasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/faturas': typeof FaturasRoute
  '/importacoes': typeof ImportacoesRoute
  '/insights': typeof InsightsRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/recorrencias': typeof RecorrenciasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/cartoes'
    | '/categorias'
    | '/configuracoes'
    | '/faturas'
    | '/importacoes'
    | '/insights'
    | '/metas'
    | '/orcamentos'
    | '/recorrencias'
    | '/relatorios'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/cartoes'
    | '/categorias'
    | '/configuracoes'
    | '/faturas'
    | '/importacoes'
    | '/insights'
    | '/metas'
    | '/orcamentos'
    | '/recorrencias'
    | '/relatorios'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/cartoes'
    | '/categorias'
    | '/configuracoes'
    | '/faturas'
    | '/importacoes'
    | '/insights'
    | '/metas'
    | '/orcamentos'
    | '/recorrencias'
    | '/relatorios'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  CartoesRoute: typeof CartoesRoute
  CategoriasRoute: typeof CategoriasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FaturasRoute: typeof FaturasRoute
  ImportacoesRoute: typeof ImportacoesRoute
  InsightsRoute: typeof InsightsRoute
  MetasRoute: typeof MetasRoute
  OrcamentosRoute: typeof OrcamentosRoute
  RecorrenciasRoute: typeof RecorrenciasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrencias': {
      id: '/recorrencias'
      path: '/recorrencias'
      fullPath: '/recorrencias'
      preLoaderRoute: typeof RecorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  CartoesRoute: CartoesRoute,
  CategoriasRoute: CategoriasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FaturasRoute: FaturasRoute,
  ImportacoesRoute: ImportacoesRoute,
  InsightsRoute: InsightsRoute,
  MetasRoute: MetasRoute,
  OrcamentosRoute: OrcamentosRoute,
  RecorrenciasRoute: RecorrenciasRoute,
  RelatoriosRoute: RelatoriosRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
